# Generated by Django 4.2.11 on 2024-04-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('source', models.IntegerField(choices=[(0, 'CHAT_GPT'), (1, 'GEMINI')])),
                ('blocked', models.BooleanField(default=False)),
                ('error', models.TextField(default='')),
                ('action_required', models.BooleanField(default=False, null=True)),
                ('action_level', models.IntegerField(choices=[(0, 'CLEAR'), (1, 'Warning'), (2, 'Alert')], default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
