# Generated by Django 4.2.11 on 2024-04-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmquery',
            name='action_level',
            field=models.IntegerField(choices=[(0, 'CLEAR'), (1, 'WARNING'), (2, 'ALERT')], default=0, null=True),
        ),
    ]
