# Generated by Django 4.2.11 on 2024-04-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='title',
            field=models.CharField(default='temp', max_length=100),
            preserve_default=False,
        ),
    ]
