# Generated by Django 4.2.11 on 2024-04-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_file_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
